### ISSUE TITLE
Proposal: Build System with Auto Deploy

### ISSUE THREAD

**Issue by abrenner** [afringer/Haku#10]
## Abstract

[Haku](https://github.com/afringer/Haku) does not have a build system with auto deploy. This means when code gets merged into master, after a review process, the program may crash due to issues not caught / fixed during a normal PR process. There is also a burden to @afringer to manually redeploy the bot. This will leave a many day gap between when code is merged to master and when its deployed into production.

The goal of this proposal is for the community to reach a decision on which of the many tools should be used to satisfy our needs. I have proposed these are the most important requests of build and auto deploy system:

1. No cost. If we require to additional infrastructure, we can do so on @afringer VM or on @abrenner network
2. Integrate with GitHub so that on each PR request, an automated build process will run. The specifics on what gets run is out of scope. The tool needs to be flexible to allow the community to run any number of tasks. Most common tasks include compile code and run a test suite
3. Once code has been merged to master, it redeploys [Haku](https://github.com/afringer/Haku) on @afringer VM
4. Implementation is out of scope

### SaaS Based Tools

- [x] [Travis CI](https://travis-ci.org/)
(selected for auto deploy system)

### Self-Hosted Tools

- [ x] [Jenkins](https://jenkins.io/)

thanks,
/adam

### SaaS Based Tools

- [x] [Circle CI](https://circleci.com/)
- [x] [Code Ship](https://codeship.com/)
- [x] [Buddy Git](https://buddy.works/)

## Self-Hosted Tools

- [x] [Team City](https://www.jetbrains.com/teamcity/)

### Thinking outside the Trapezoid

- [x] Move VCS to BitBucket as it has built in Pipelines
- [x] Move VCS to GitLab as it has built in CI/CD

**Comment by afringer** [comment]
I'll roll with anything, I've got 0 experience setting up a CI system, and only really worked with them indirectly if at all. I'll work with whatever you all think is best (I think a while ago Matt recommended Jenkins). I like bitbucket (and all of the associated products) but private with a max of 5 seems a little restrictive. I like the idea of interested parties following development (though if that will happen is another issue altogether)

**Comment by abrenner** [comment]
@afringer I realize that I probably gave to many options in my initial proposal. I went ahead and limited it two the top two which will satisfy our immediate and medium needs. First post updated to reflect that. 

My take on things:
I have had great success setting up and deploying Jenkins, but I am also willing to learn something new like Travis CI. If I had to choose, I would say lets try something new and go with Travis CI. If for what ever reason it does not work out, we can switch to self-hosted Jenkins solution which will definitely fit our needs.

I await others feedback and suggestions.

**Comment by matsprehn** [comment]
As long as we can have configuration as code, I'm okay with whatever we choose. I haven't used Travis before, but it looks similar to gitlab pipelines. I'm also very much in favor of us setting up a test suite and having that run automatically against any Pull Requests against the repository.

**Comment by jromovel** [comment]
I haven't used either so I'm up for learning Travis with everyone else.

**Comment by abrenner** [comment]
Sounds like Travis-CI is the winner. I will go ahead and close this out and create a new story for getting it to work.

Thanks everyone!
