### ISSUE TITLE
FIX: Word Matching

### ISSUE THREAD

**Issue by abrenner** [afringer/Haku#12]
Haku does not match on words causing unexpected behavior.

Test Case:

Expected Input: yee
Expected Output:
https://github.com/afringer/Haku/blob/34e9cbe867656f1461bc23645ef42a239324c9c4/responses.js#L173

Expected Input: emplo**yee**
Expected Output: Nothing
Unexpected Output:
https://github.com/afringer/Haku/blob/34e9cbe867656f1461bc23645ef42a239324c9c4/responses.js#L173

**Comment by jromovel** [comment]
@abrenner would this fall under the expected input
"lets yee this thing"

**Comment by abrenner** [comment]
> @abrenner would this fall under the expected input
> "lets yee this thing"

We should expect the Haku to respond in this case since yee stands on its own -- space before and after. However, Haku should not respond when it sees emplo**yee** or pa**yee**s. 

The logic in the code needs to check for word matching as it currently does character matching. Probably safe to assume a word is a collection of characters that are separated by a space.
